### ISSUE TITLE
early todo

### ISSUE THREAD

**Issue by mdsumner** [hypertidy/gdalio#1]
- [ ] need a proper source not broken netcdf
- [x] illustrate the resampling options with the gdalio_data() output
- [x] create a small vrt() wrapper to add augmentation to a dsn string

## vrt wrapper

This could be a function `vrt(dsn, src_extent, src_projection)` and it just updates the data on read via `vapour_warp_raster()`. More fleshed out it could create the actual VRT (so we could do reorients and shifts and subsets and calcs and so forth).
